import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavigationBar />
        <main className="flex min-h-screen flex-col items-center justify-between py-4">
          <div className="">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
